export const SPOTS_ITMES = [
  { zh_name: '臺北市', en_name: 'Taipei' },
  { zh_name: '新北市', en_name: 'NewTaipei' },
  { zh_name: '桃園市', en_name: 'Taoyuan' },
  { zh_name: '臺中市', en_name: 'Taichung' },
  { zh_name: '臺南市', en_name: 'Tainan' },
  { zh_name: '高雄市', en_name: 'Kaohsiung' },
  { zh_name: '基隆市', en_name: 'Keelung' },
  { zh_name: '新竹市', en_name: 'Hsinchu' },
  { zh_name: '新竹縣', en_name: 'HsinchuCounty' },
  { zh_name: '苗栗縣', en_name: 'MiaoliCounty' },
  { zh_name: '彰化縣', en_name: 'ChanghuaCounty' },
  { zh_name: '南投縣', en_name: 'NantouCounty' },
  { zh_name: '雲林縣', en_name: 'YunlinCounty' },
  { zh_name: '嘉義縣', en_name: 'ChiayiCounty' },
  { zh_name: '嘉義市', en_name: 'Chiayi' },
  { zh_name: '屏東縣', en_name: 'PingtungCounty' },
  { zh_name: '宜蘭縣', en_name: 'YilanCounty' },
  { zh_name: '花蓮縣', en_name: 'HualienCounty' },
  { zh_name: '臺東縣', en_name: 'TaitungCounty' },
  { zh_name: '金門縣', en_name: 'KinmenCounty' },
  { zh_name: '澎湖縣', en_name: 'PenghuCounty' },
  { zh_name: '連江縣', en_name: 'LienchiangCounty' },
];
